#!/usr/bin/env bash
# Cloud Agent install phase: prepare a self-contained development environment.
# Idempotent — safe to run repeatedly and against cached/snapshot state.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
# shellcheck source=db.sh
source "$REPO_ROOT/.cursor/db.sh"

echo "==> Ensuring PostgreSQL is installed"
if ! command -v pg_lsclusters >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

echo "==> Starting PostgreSQL and provisioning the app database"
start_postgres
ensure_role_and_db

echo "==> Writing local .env (only if missing)"
if [ ! -f "$REPO_ROOT/.env" ]; then
  cat > "$REPO_ROOT/.env" <<'ENV'
# Local Cloud Agent development environment (generated by .cursor/install.sh).
# Local Postgres provisioned inside the VM. Do NOT use for production.
DATABASE_URL=postgresql://spsv:spsv@127.0.0.1:5432/spsv?schema=public
DATABASE_URL_UNPOOLED=postgresql://spsv:spsv@127.0.0.1:5432/spsv?schema=public
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=dev-only-secret-not-for-production
ENV
fi

echo "==> Installing Node dependencies (runs prisma generate via postinstall)"
npm ci

echo "==> Syncing Prisma schema to the local database"
npx prisma db push --skip-generate

echo "==> Install complete"
